### ISSUE TITLE
How to change base_uri for Unit Test

### ISSUE THREAD

**Issue by mistre83** [someline/someline-starter#10]
I've setup the new version of Someline (Laravel 5.3) and it point to http://someline-starter-demo.app but when i run unit test i get this error:

```
Connection timeout:
REST CLIENT SERVICE: local, ENVIRONMENT: dev
REST CLIENT BASE URI: http://someline-starter.app/
```

I'm looking the video tutorial (the new video version, that is related to Laravel 5.2) and this show how to modify the base_uri in `BaseApiTestCas.php`

But in this new version the structure has changed and i dont find how to change that URI.

**Comment by mistre83** [comment]
Right now i changed my url to http://someline-starter.app to continue study it , but i would like to change this url in the future.

Now, when i run the test i get another error:

```
Response STATUS CODE is 401:
Array
(
    [error] => invalid_client
    [message] => Client authentication failed
)

Failed to get access token for grant type [password]!
```

**Comment by libern** [comment]
You may need to update the `local` service in `config/rest-client.php` .

**Comment by mistre83** [comment]
Thanks.
For the second question you have some suggestion ? Or prefeer i remove it from this thread and oper another ?

**Comment by libern** [comment]
Close and open another :)
