### ISSUE TITLE
Unit Testing Someline V0.3.4 - Failed to get access token.

### ISSUE THREAD

**Issue by mistre83** [someline/someline-starter#11]
I did tried to setup the version 0.3.4 of Someline Starter but when i run Unit test i get the follow error:

```
Response STATUS CODE is 401:
Array
(
    [error] => invalid_client
    [message] => Client authentication failed
)

Failed to get access token for grant type [password]!
```

I run all the commands, the oauth_* tables are populated but i get the error `Failed to get access token`...

I'm trying to run the pre-built test of Users. Too difficult at the moment write other tests... :)

**Comment by libern** [comment]
API and Unit Tests

Note: You may need to change the local service configs under dev environment from config/rest-client.php to fit your local development configurations.

**Comment by mistre83** [comment]
Thanks now i try!

ps: yesterday i have leave a comment in your youtube video. I think this project is wonderful, this have all setup for backend and frontend very well organized! 
If i can give you an advice... you should do a video where you create a full project with this... 
This project can grow and grow!!! :)) Really nice work!

**Comment by libern** [comment]
Also change the value of `API_TEST_CLIENT_SECRET` in `.env` file to the `secret` value of `Password Grant Client` record  in `oauth_clients` table.

**Comment by mistre83** [comment]
Thanks, i have copied the `secret` value from `oauth_client` table into `.env` and it works!
