### ISSUE TITLE
"AccessDeniedHttpException" while seeding new model 

### ISSUE THREAD

**Issue by reehan79** [someline/someline-starter#12]
The UsersTableSeeder works well and also passes all the tests; however, when I created a new model "Post" according to the guide, it throws "[Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException] " while seeding. 
I have also checked on Tinker, it was there for Post model but not for the User model.
Can you give me some pointers that how to resolve it?

**Comment by reehan79** [comment]
while saving,  $model->onSaving(); event is called which asks for current_auth_user();, however during seeding, how to provide a $User?

**Comment by libern** [comment]
You can use `\Auth::loginUsingId(1);` before you calling the seeder command.

**Comment by reehan79** [comment]
Ok. That  works. Thanks

**Comment by reehan79** [comment]
Ok. That works. Thanks

**Comment by reehan79** [comment]
Ok. That works. Thanks
