### ISSUE TITLE
[Question] Any Role-based permission model ?

### ISSUE THREAD

**Issue by reehan79** [someline/someline-starter#13]
Can you suggest any role-based permission package compatible with Someline starter? I have tried spatie/laravel-permission; however, its not working.

**Comment by libern** [comment]
This should be help. [https://github.com/Zizaco/entrust](https://github.com/Zizaco/entrust)

**Comment by folkevil** [comment]
vote for entrust

**Comment by reehan79** [comment]
Thanks for the suggestions!
