### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by marcamon2013** [someline/someline-starter#14]
`Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL
  : alter table `password_resets` add index `password_resets_email_index`(`email`))`

Using MariaDB 10.1

**Comment by libern** [comment]
It could be caused by the schema is utf8mb4 error, try changing to utf8~

**Comment by marcamon2013** [comment]
Thanks but i don't understand why it's recommended use do to this
`CREATE DATABASE `someline_starter` DEFAULT CHARACTER SET = `utf8mb4` DEFAULT COLLATE = `utf8mb4_unicode_ci`;`

**Comment by libern** [comment]
Because utf8mb4 support store of emoji characters, where utf8 doesn't

**Comment by marcamon2013** [comment]
Thanks for this information.

**Comment by coding-sunshine** [comment]
I am still getting the same error :( @donmarkus  how did you solve it?
