### ISSUE TITLE
主键的问题

### ISSUE THREAD

**Issue by osdebianly** [someline/someline-starter#16]
安装一些其他扩展，默认使用 user 表 id 作为主键， 但这里用的是 user_id ，给操作带来一些不便

**Comment by libern** [comment]
可否举例？

**Comment by osdebianly** [comment]
例如这个(trexology/laravel-order)[https://github.com/Trexology/laravel-order]

主键名字应该是设成 id还是 #tablename_id 比较好？ (这里13楼有问)[https://ruby-china.org/topics/26352]

**Comment by libern** [comment]
推荐#tablename_id，然后在model里替换
