### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by willmkt** [someline/someline-starter#2]
Hi, i looked at this project and it is very nice.

it would be nice to implement a generator to do all the heavy work.

Thanks..

**Comment by libern** [comment]
Could you suggest what are the heavy work you are referring to?

**Comment by libern** [comment]
The new version from `v0.3.6` onwards, there are `php artisan starter:entity` for auto generate support.

**Comment by geoidesic** [comment]
`php artisan starter:entity` gives error: `Not enough arguments (missing: "name").`
