### ISSUE TITLE
Vue i18n cannot translate

### ISSUE THREAD

**Issue by Germanaz0** [someline/someline-starter#29]
I am getting the following error:

```[vue-i18n] Cannot translate the value of keypath "user.users". Use the value of keypath as default```

I do not know how to generate them, thanks

**Comment by libern** [comment]
Try the latest release `v0.4.2`.

```
https://github.com/someline/someline-starter/releases/tag/v0.4.2
```

**Comment by Germanaz0** [comment]
@libern updated, I am using Nginx and somehow the status code that locales return is 404, but when I open the url in the browser I can see the content.

Curious fact, If I force setting the headers into `LocaleController` to 200, it is still return 404 code.

```
curl -I http://platform.dev/locales/en.js\?d4b3571aaa

> HTTP/1.1 404 Not Found
> Server: nginx/1.10.3
```

**Comment by Germanaz0** [comment]
It was a missconfiguration from nginx, thanks for the help
