### ISSUE TITLE
Error while running php artisan route:list

### ISSUE THREAD

**Issue by enimiste** [someline/someline-starter#4]
Hi,

  i have this error while running the command `php artisan route:list` : 
  

> [ReflectionException]                                          
>   Class Someline\Http\Controllers\HomeController does not exist 

**Solution :** 

- Remove the line from Http/routes.php file
- Add a HomeController to the project

**Another issue :** I dont see Api routes in the result of that command, why ?

Thanks

**Comment by libern** [comment]
Use `php artisan api:routes` to see api routes

**Comment by libern** [comment]
`v0.0.6` has released in addressing your issue

**Comment by enimiste** [comment]
I think it is difficult to update project with new releases.

It would be better to make Someline specific features (Base*, ...) into a separated package and require it in composer.json

This way we can do `composer update` and get the new fixes and features.

**Comment by libern** [comment]
@enimiste Hi, new version has been released. This time has use the someline/starter-framework package.

**Comment by enimiste** [comment]
Good news.

Check this package [Float Number and Arithmetique calculs For Laravel 5](https://packagist.org/packages/enimiste/l5-math)

I work with for financial calculation (arithmetic one for now). take a see on it.

Have you a Slack channel to discusse out of issues page ?

**Comment by libern** [comment]
You need to completely reinstall this time. Cant simply update. Because the structure changes.

**Comment by Muhammadinaam** [comment]
Hi, this is a nice package but I think that the developers have stopped working on it. Maybe you can try this package: https://github.com/Muhammadinaam/speed-admin. It supports Laravel 8+.
