### ISSUE TITLE
How to change timezone?

### ISSUE THREAD

**Issue by zcdll** [someline/someline-starter#58]
I want to change the timezone, I have changed the timezone in `config/app.php` to `'timezone' => 'PRC'`.
And when I check the database, I found the field I added myself showed the correct time, however the default field added by the Framework itself `created _at`, `updated_at` showed the UTC time.

I want to know whether exits a place to change the framework timezone?

Thx!

**Comment by skyeryg** [comment]
In your app\Models\BaseModel.php
Add 
```
protected $timestamp_always_save_in_utc = false;
protected $timestamp_get_with_user_timezone = false;

**Comment by zcdll** [comment]
It's done!

Thanks a lot!
