### ISSUE TITLE
Getting error while "php artisan migrate"

### ISSUE THREAD

**Issue by GaneshKandu** [someline/someline-starter#83]
Hi,

Getting Error on ```php artisan migrate``` command

only 3 tables are getting created `migrations`, `password_resets`, `users`;

here is output file of ```php artisan migrate > artisan_migrate.txt```
full path is removed in output

[artisan_migrate.txt](https://github.com/someline/someline-starter/files/2118304/artisan_migrate.txt)

**Steps i followed**
- composer install
- cp .env.example .env
- chmod -R 777 storage bootstrap/cache
- php artisan key:generate
- php artisan migrate ( database already created and .env configured  )

**system environment**

-  PHP: 7.1.18
-   MySQL: 5.7.22
-   SQLite installed

```js
Migration table created successfully.

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `password_resets` add index `password_resets_email_index`(`email`))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141

  Please use the argument -v to see more details.

```

**Comment by libern** [comment]
You need to provide max length for any $table->string("column", 188);

**Comment by vidhi041** [comment]
After adding Schema::defaultStringLength(191); to AppServiceProvider::boot(), You need to change
'engine' => 'InnoDB', in config/database.php in mysql.

It is working for me !

**Comment by GaneshKandu** [comment]
thanks @vidhi041 working now

**Comment by princencu94** [comment]
@GaneshKandu where did you find the Schema::defaultStringLength(191); code

**Comment by GaneshKandu** [comment]
@princencu94

app/Providers/AppServiceProvider.php

```php
public function boot()
{
    Schema::defaultStringLength(191);
}
```

add this in ```boot`` function

**Comment by GaneshKandu** [comment]
@princencu94

app/Providers/AppServiceProvider.php

```php
public function boot()
{
    Schema::defaultStringLength(191);
}
```

add this in ```boot``` function

**Comment by Muhammadinaam** [comment]
Hi, this is a nice package but I think that the developers have stopped working on it. Maybe you can try this package: https://github.com/Muhammadinaam/speed-admin. It supports Laravel 8+.
